#!/usr/bin/env bash
# Generate a Homebrew formula for the panex tap.
#
# Usage:
#   scripts/generate-homebrew-formula.sh --version v0.1.0
#
# The script fetches the SHA256SUMS manifest from the GitHub release and emits
# the formula to stdout. Pipe it to a file to update the tap:
#
#   scripts/generate-homebrew-formula.sh --version v0.1.0 > Formula/panex.rb
set -euo pipefail

REPO="panex-dev/panex"

VERSION=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) shift; VERSION="${1:-}"; shift ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$VERSION" ]]; then
  echo "error: --version is required" >&2
  exit 1
fi

# Strip leading v for the formula version field.
FORMULA_VERSION="${VERSION#v}"

# Fetch the checksum manifest.
SUMS="$(gh release download "$VERSION" --repo "$REPO" --pattern '*SHA256SUMS' -O - 2>/dev/null)" \
  || { echo "error: could not download SHA256SUMS for $VERSION" >&2; exit 1; }

sha_for() {
  local os="$1" arch="$2"
  echo "$SUMS" | grep "panex_${VERSION}_${os}_${arch}.tar.gz" | cut -d' ' -f1
}

SHA_DARWIN_ARM64="$(sha_for darwin arm64)"
SHA_DARWIN_AMD64="$(sha_for darwin amd64)"
SHA_LINUX_AMD64="$(sha_for linux amd64)"
SHA_LINUX_ARM64="$(sha_for linux arm64)"

for var in SHA_DARWIN_ARM64 SHA_DARWIN_AMD64 SHA_LINUX_AMD64 SHA_LINUX_ARM64; do
  if [[ -z "${!var}" ]]; then
    echo "error: missing checksum for $var" >&2
    exit 1
  fi
done

BASE_URL="https://github.com/${REPO}/releases/download/${VERSION}"

cat <<RUBY
# typed: false
# frozen_string_literal: true

# This formula is auto-generated by scripts/generate-homebrew-formula.sh.
# Do not edit by hand.
class Panex < Formula
  desc "Development runtime for Chrome extensions"
  homepage "https://github.com/${REPO}"
  version "${FORMULA_VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE_URL}/panex_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    else
      url "${BASE_URL}/panex_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${SHA_DARWIN_AMD64}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${BASE_URL}/panex_${VERSION}_linux_arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    else
      url "${BASE_URL}/panex_${VERSION}_linux_amd64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
    end
  end

  def install
    bin.install "panex"
  end

  test do
    assert_match "panex", shell_output("#{bin}/panex version")
  end
end
RUBY
